from ament_index_python.packages import (
    get_package_prefix,
    get_package_share_directory,
)
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess
from launch.substitutions import LaunchConfiguration


def generate_launch_description():
    identify_share = get_package_share_directory('exo_identify')
    identify_prefix = get_package_prefix('exo_identify')
    return LaunchDescription([
        DeclareLaunchArgument(
            'mjcf',
            default_value=(
                f'{identify_share}/results/seven_dof/simulation_model/'
                'exo7_sim.xml'),
            description='Existing MJCF generated by mujoco_model.py',
        ),
        DeclareLaunchArgument(
            'parameters',
            default_value=(
                f'{identify_share}/results/seven_dof/'
                'dynamics_identification/identified_parameters_sim.npz'),
            description='Identified .npz model or exported gravity .json',
        ),
        DeclareLaunchArgument(
            'config',
            default_value=f'{identify_share}/config/identification.json',
        ),
        DeclareLaunchArgument(
            'urdf',
            default_value=(
                f'{identify_share}/urdf/exo.SLDASM/urdf/'
                '\u88c5\u914d\u4f53.SLDASM.urdf'),
        ),
        DeclareLaunchArgument('duration', default_value='0.0'),
        DeclareLaunchArgument('speed', default_value='1.0'),
        ExecuteProcess(
            cmd=[
                f'{identify_prefix}/lib/exo_identify/'
                'mujoco_compensation_sim.py',
                '--mjcf', LaunchConfiguration('mjcf'),
                '--parameters', LaunchConfiguration('parameters'),
                '--config', LaunchConfiguration('config'),
                '--urdf', LaunchConfiguration('urdf'),
                '--duration', LaunchConfiguration('duration'),
                '--speed', LaunchConfiguration('speed'),
            ],
            output='screen',
        ),
    ])
